version: '3.2'

services:

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
    env_file:
      - ./neo4j/.env
    volumes:
      - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/logs:/var/lib/neo4j/logs

    build: ./runner
    ports:
      - 4002:4002
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
    env_file:
      - ./runner/.env
    volumes:
      - ./runner:/app
      - type: bind
        source: ./.git
        target: /app/.git
        read_only: true
    depends_on:
      - neo4j
      - node

  node:
    image: rinzlerfr/idena-node:latest
    ports:
      - 9009:9009
      - 9999:9999
      - 40404:40404
      - 40405:40405
      - 50505:50505
      - 50506:50506
    volumes:
      - ${IDENA_DATA_DIR}:/datadir
    tty: true 
    stdin_open: true